# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Comanda < Formula
  desc "Chain of Models and Actions - declarative LLM workflow orchestration"
  homepage "https://github.com/kris-hansen/comanda"
  version "0.0.175"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kris-hansen/comanda/releases/download/v0.0.175/comanda-darwin-amd64.tar.gz"
      sha256 "32a4fbcaddddd9f7695311751ac8c39bc6587adbef9ede54d014162fe99cda1f"

      define_method(:install) do
        bin.install "comanda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kris-hansen/comanda/releases/download/v0.0.175/comanda-darwin-arm64.tar.gz"
      sha256 "2ba9dba7188cb526a1ff8a3cfe80b9fdede9c66b69b8cd0875b6d25fa6c3c045"

      define_method(:install) do
        bin.install "comanda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kris-hansen/comanda/releases/download/v0.0.175/comanda-linux-amd64.tar.gz"
      sha256 "70a626e8fed2b41d8b1a236ed0edaadd6ee81240b458f7b743f646457a59ed0c"
      define_method(:install) do
        bin.install "comanda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kris-hansen/comanda/releases/download/v0.0.175/comanda-linux-arm64.tar.gz"
      sha256 "207692b758e59320911d8ba5842c0583975f290234bcd254015acb0b30804c91"
      define_method(:install) do
        bin.install "comanda"
      end
    end
  end

  test do
    system "#{bin}/comanda", "version"
    system "#{bin}/comanda", "help", "configure"
  end
end
