# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Comanda < Formula
  desc "Chain of Models and Actions - declarative LLM workflow orchestration"
  homepage "https://github.com/kris-hansen/comanda"
  version "0.0.225"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kris-hansen/comanda/releases/download/v0.0.225/comanda-darwin-amd64.tar.gz"
      sha256 "41e660dcb69d86c646446b28f1350794788b029cf6662bd57b44e4459f6cb23e"

      define_method(:install) do
        bin.install "comanda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kris-hansen/comanda/releases/download/v0.0.225/comanda-darwin-arm64.tar.gz"
      sha256 "e4583d6a60e3f354670f618fa89f274fb8c261e7bb0108a4fc956cb9225e9873"

      define_method(:install) do
        bin.install "comanda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kris-hansen/comanda/releases/download/v0.0.225/comanda-linux-amd64.tar.gz"
      sha256 "9874ffa7bb993ca5cb1c99f03fa9c74910b731820aa32e45f6ac8bac0596c94c"
      define_method(:install) do
        bin.install "comanda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kris-hansen/comanda/releases/download/v0.0.225/comanda-linux-arm64.tar.gz"
      sha256 "8c0344d50c04bc45f3ed471b317c83e35662674d6a4a6bb68c1d771989270e4d"
      define_method(:install) do
        bin.install "comanda"
      end
    end
  end

  test do
    system "#{bin}/comanda", "version"
    system "#{bin}/comanda", "help", "configure"
  end
end
