# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Comanda < Formula
  desc "Chain of Models and Actions - declarative LLM workflow orchestration"
  homepage "https://github.com/kris-hansen/comanda"
  version "0.0.247"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kris-hansen/comanda/releases/download/v0.0.247/comanda-darwin-amd64.tar.gz"
      sha256 "a1f0423910e42b93ec38f9cab2804d4989fd4e41acf76bb2ebd40fb92ec7842a"

      define_method(:install) do
        bin.install "comanda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kris-hansen/comanda/releases/download/v0.0.247/comanda-darwin-arm64.tar.gz"
      sha256 "8be8f30c565b02182d4260d3dbbaa859822057e0f06d732aec15172e09311719"

      define_method(:install) do
        bin.install "comanda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kris-hansen/comanda/releases/download/v0.0.247/comanda-linux-amd64.tar.gz"
      sha256 "190f8a9f4fe2a9f10a990b422ec9b392558902f35c3832ca96940c4e359abb99"
      define_method(:install) do
        bin.install "comanda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kris-hansen/comanda/releases/download/v0.0.247/comanda-linux-arm64.tar.gz"
      sha256 "6310cca01ba5f166d02d6e32b7239456e48877925360539d76377994348745b3"
      define_method(:install) do
        bin.install "comanda"
      end
    end
  end

  test do
    system "#{bin}/comanda", "version"
    system "#{bin}/comanda", "help", "configure"
  end
end
